### ISSUE TITLE
dont panic on yaml frontmatter with non string

### ISSUE THREAD

**Issue by adam-stokes** [drone/jkl#8]
If you set something like 

---
## categories: [test, linux]

jkl will panic as it doesn't understand that type due to expecting a string. Maybe something to either ignore or log the error would be helpful. This was mainly coming up for me when migrating existing jekll/octopress posts that allow categories tag into jkl.

thanks!

**Comment by bradrydzewski** [comment]
thanks Adam ... should be easy enough to fix. The issue is with the following code in `page.go`:

``` go
// Gets a parameter value as a string array.
func (p Page) GetStrings(key string) (strs []string) {
    if v, ok := p[key]; ok {
        strs = v.([]string)
    }
    return []string{}
}
```

I'll need to modify the code to test that `v` is type `[]string` OR `[]interface{}` ... and if it is `[]interface{}` I think I can get the string values of each item using the reflection package ...

**Comment by adam-stokes** [comment]
Cool sounds good -- ill also do some digging around and can also test as well.. I've got everything else setup and it works great

**Comment by abh** [comment]
You shouldn't need to use reflect, you can do something along the lines of

``` go
switch v.(type): {
    case string:
        // it's a string
    case []string:
        // array of strings
    case ...:
}
```

**Comment by adam-stokes** [comment]
:\
