### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by jamtur01** [drone/jkl#9]
Any plans to support this on OSX? The current use of inotify means it won't build there.

Pointers to make it work (newcomer to Go) also welcome.

Thanks

**Comment by bradrydzewski** [comment]
check out this fork:
https://github.com/tetleyt/jkl/blob/master/watch_posix.go

go has a concept of "compiler tags" that can instruct the compiler to include or exclude files based on operating system. The above fork will exclude the inotify code for non-linux systems by moving the inotify code to `watch.go`, creating a `watch_posix.go` with the following compiler directives:

```
// +build darwin freebsd netbsd openbsd windows
```

I'll see if I can merge his changes

**Comment by abh** [comment]
There's also https://github.com/howeyc/fsnotify

**Comment by bradrydzewski** [comment]
just merged a pull request to add osx support. thanks to @abh
